version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  web: &myapp
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_PASSWORD=password
      - MYSQL_SOCKET=""
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  webpack:
    <<: *myapp
    command: /bin/sh -c "bundle install && yarn install --check-files && bin/webpack-dev-server"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      BUNDLE_APP_CONFIG: ./.bundle
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - 3035:3035
    tty: true
    stdin_open: true
    depends_on:
      - web

volumes:
  mysql-data:
    driver: local
  tmp-data:
  log-data: